//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class table1
    {
        public int key { get; set; }
        public Nullable<int> intData { get; set; }
        public string stringData { get; set; }
        public Nullable<System.DateTime> datetimeData { get; set; }
    }
}
